source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CFAToolKit_Example', :exclusive => true do
  pod "CFAToolKit", :path => "../"
end

target 'CFAToolKit_Tests', :exclusive => true do
  pod "CFAToolKit", :path => "../"

  
end
